language: php

# php compatibility
php: ["7.2", "7.3", "7.4", "8.0"]

cache:
  - directories:
    - $HOME/.composer

env:
  global:
    - PHP_CS_FIXER_IGNORE_ENV=yes

before_script:
  - travis_retry composer install --no-interaction --prefer-dist
  - phpenv config-rm xdebug.ini

script:
  - vendor/bin/phplint
  - vendor/bin/php-cs-fixer fix --verbose
  - vendor/bin/phpcbf --colors -sp src/ tests/
  - vendor/bin/phpunit --testdox --verbose
  - vendor/bin/phpstan.phar analyse --no-progress --level max src/ tests/

notifications:
  email: false
